

 <div class="block">
 <h1 class="sz4 margin" style="border-bottom:10px solid black ">Ruchi Doctor</h1>
 </div>
 <div class="row block">
  <div class="col-50">
   <img src="/img/ruchi.jpg" width="100%">
  </div>
   <div class="col-50">
    <div class="row">
     <div class="col-100">
      <h1 class="Share sz4 cs0"  style="margin-top:0px;margin-bottom:-10px" ><strong>Leader Entrepreneur</strong></h1>
      <p class="szhalf"><span class="bg-color-red text-color-white" style="font-weight:bold;padding:2px">She</span> is 21st century girl, born in 20th century! There have been many a woman, who has been born in too demanding social and family conditions, and Ruchi is no exception. She was born in a lower middle class, deeply traditional Jain Guajarati family, in a world of stuck up MCPs, with wolves prowling all over, in the guides of human forms. Not only had the home that was loaded with thick chaos, commotion, parents at each other's throats. Mercifully, Ruchi was not the one to cow down in such perpetual inimical, threatening, hostile environ. She never took any bullshit dished out to her in various, disgusting cuisines, rather was focused, determined, and hopeful and empowered.</p>
      <p class="szhalf"><span class="bg-color-red text-color-white" style="font-weight:bold;padding:2px">She</span> was born, a pro-woman alpha woman, cultivating a meaningful life for a liberated woman, to celebrate life, even though it could be intimidating, yet she never failed to invest in herself, to become tough enough, to be of help for all those sisters, who may not have the zeitgeist, needed, to live with dignity in herself, in eco space chosen by her, for her life.</p>
      <p class="szhalf"><span class="bg-color-red text-color-white" style="font-weight:bold;padding:2px">She</span> is a hands-on, person who is a go getter, and makes thing happen. Indeed, her fearlessness is contagious. She has always believed that success is not the key to happiness; rather it is the happy women who become successful. Following her own paradigm, she is perpetually in bloom, celebrating forever the spring, where she sings like a nightingale, both in defeat and victories. Thus, she defines success in her own way, and achieving it in her exemplary way and imbibing it in her life, indeed, to pour it over all other, who came close to her Midas touch, both men and women. Like Hillary Clinton, she strongly believes that every girl born has the right to achieve her dreams, and bloody well, she should do it. Her courage lies in her innate strength to recognize her fears and bravely combat them. While combating thus, she just does not dream for success, but makes it happen.</p>
      <p class="szhalf"><span class="bg-color-red text-color-white" style="font-weight:bold;padding:2px">She</span> has made her success happen right from her childhood. Family was in relentless turmoil, where parents were forever wrangling, making the home in to a long-lasting battle ground, in two people, who never knew, why they came together and for what; more so, they could never ponder on the damaging influence their incessant squabbling would have, on the tender psyche of their children. Surprisingly, Ruchi kept her cool, with her determination never, ever wavering! She had promised herself, to overcome all the demanding obstacles, thwarting her effort, for her rightful, blissful, prosperous life.  Early in life, she had learned the truth that no one would give her anything; she would have to get it for herself with relentless, efforts, many times more than any man, in a man’s world.</p>
      <p class="szhalf"><span class="bg-color-red text-color-white" style="font-weight:bold;padding:2px">She</span> was inspired by the idea of chasing her bucket list dreams. No longer willing to settle for the lives she felt she should be living, she kept deciding what she wanted to!  She always believed that nothing worth fighting for could be achieved without struggle. And she worked real hard, even to the point being cruel to herself, to excel in her studies. It was because of this, she has under her belt, IT Diploma,  MA English, MA Gujarati etc. It is this dedication and Arjun like focus that all the tumultuous upheavals in her personal life could Never discourage her, from, not only perusing her dreams of success, but actually achieving them.</p>
     </div>
    </div>
  </div>
 </div>
